### ISSUE TITLE
HeaderDefinedLengthProtocol constructor, lengthCalculator parameter not used

### ISSUE THREAD

**Issue by aglover-cayan** [TSYS-Merchant/tcp-stumps#1]
In the HeaderDefinedLengthProtocol constructor, _lengthCalculator is assigned using `_lengthCalculator` again instead of the `lengthCalculator` method parameter.

https://github.com/Cayan-LLC/tcp-stumps/blob/ac230204b22d975ccaa91669ef6c0258454e0684/src/TcpStumps.Base/HeaderDefinedLengthProtocol.cs#L26

**Comment by mwmharrington** [comment]
Fix available in v0.1.0
